finalproject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView, PasswordResetConfirmView
from django.urls import path, include

from core.views import frontpage, about
from userextend.forms import AuthenticationLoginForm, PasswordChangeFormExtend, PasswordResetFormExtend, \
    SetPasswordFormExtend

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainPage.urls')),
    path('core/', frontpage, name='frontpage'),
    path('about/', about, name='about'),
    path('', include('ganduri.urls')),
    path('login/', LoginView.as_view(form_class=AuthenticationLoginForm), name='login'),
    path('password_change/', PasswordChangeView.as_view(form_class=PasswordChangeFormExtend), name='password_change'),
    path("password_reset/", PasswordResetView.as_view(form_class=PasswordResetFormExtend), name="password_reset"),
    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(form_class=SetPasswordFormExtend)),
    path('', include('django.contrib.auth.urls')),
    path('',include('userextend.urls')),
    path('', include('foodies.urls')),
    path('contact/',include('contact.urls')),
    path('todo/',include('todoapp.urls')),
]

foodies/urls.py
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('', views.homeview, name='homepage'),
    path('recipes/', views.FoodieListView.as_view(), name='recipes'),
    path('recipe/<int:recipe_id>/create_rating/', views.rating, name='create_rating'),
    path('recipe/detail_recipes/<int:pk>/',views.DetailFoodiesView.as_view(),name='detail-view')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home')
]

foodies/models.py
from django.db import models
from autoslug import AutoSlugField

from userextend.models import UserExtend


class Topic(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from="title",max_length=200)

    def __str__(self):
        return self.title

class Recipe(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from="title",max_length=200)
    image = models.ImageField(upload_to='media/',null=True,blank=True)
    description = models.TextField()
    ingredients = models.TextField()
    directions = models.TextField()
    servings = models.CharField(max_length=5)
    time = models.CharField(max_length=5)
    calories = models.CharField(max_length=5)
    fat = models.CharField(max_length=5)
    carbs = models.CharField(max_length=5)
    protein = models.CharField(max_length=5)
    topic = models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.title


class Rating(models.Model):
    recipe = models.ForeignKey(Recipe,on_delete=models.CASCADE)
    user = models.ForeignKey(UserExtend,on_delete=models.CASCADE)
    number = models.IntegerField()

foodies/forms.py
from django import forms
from django.forms import ModelForm

from foodies.models import Rating


class RatingForm(ModelForm):
    class Meta:
        model = Rating
        fields = ['recipe', 'user', 'number']
        widgets = {
            'recipe': forms.HiddenInput(),
            'user': forms.HiddenInput(),
            'number': forms.NumberInput()
        }

foodies/views.py
from functools import reduce

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView

from foodies.forms import RatingForm
from foodies.models import Recipe, Rating
from django.db.models import Q, Sum
from django.shortcuts import render
from django.views.generic.edit import CreateView, FormView

from userextend.models import UserExtend


def homeview(request):
    return render(request, 'MainPage/index.html')


class FoodieListView(ListView, LoginRequiredMixin):
    model = Recipe
    context_object_name = 'recipes'
    template_name = 'foodies/search_foodies.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'keywords' in self.request.GET:
            keywords = self.request.GET['keywords'].split()
        else:
            keywords = []
        topics = list(self.request.GET.keys())
        if 'keywords' in topics:
            topics.remove('keywords')
        filter_keywords_query = Q()
        for keyword in keywords:
            filter_keywords_query |= Q(title__icontains=keyword)
        filter_topics_query = Q()
        for topic in topics:
            filter_topics_query |= Q(topic__title__icontains=topic)

        recipes = self.get_queryset().filter(filter_keywords_query & filter_topics_query)
        context['recipes'] = recipes
        context['rating_form'] = RatingForm()

        return context


class CreateRatingView(CreateView, LoginRequiredMixin):
    form_class = RatingForm
    model = Rating
    success_url = reverse_lazy('index')
    template_name = 'foodies/create_rating.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'initial': {'user': self.request.user.id, 'recipe': self.kwargs.get('pk')}})
        return kwargs


class DetailFoodiesView(DetailView, LoginRequiredMixin):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'foodies/detail_foodies.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        ratings = self.object.rating_set.aggregate(Sum('number')).get('number__sum')  # sum of ratings
        if not ratings:
            average_rating = 0
        else:
            average_rating = ratings / self.object.rating_set.count()
        data['average_rating'] = average_rating
        has_rated = Rating.objects.filter(user__id=self.request.user.id, recipe=self.object).count() >= 1
        data['has_rated'] = has_rated

        return data


@login_required
def rating(request, recipe_id):
    rating_number = int(request.POST.get('number'))
    if 0 <= rating_number <= 5:
        Rating.objects.create(recipe=Recipe.objects.get(id=recipe_id), user=UserExtend.objects.get(id=request.user.id),
                              number=rating_number)
    return redirect('detail-view', pk=recipe_id)

templates/foodies/create_rating.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create Rating {% endblock %}



{% block content %}
 <style>
    body{
        color: black;
    }

</style>


    <div class="container"><br><br>
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create rating</h3>
                        <form method="post" >
                            {% csrf_token %}
                            <div class="card-body">
                                {{ form.as_p }}
                            </div>
                            <div class="card-footer text-center">
                                <button type="submit" class="btn btn-info">Save</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div><br><br>
{% endblock %}

templates/foodies/detail_foodies.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Food Details {% endblock %}

{% block content %}


    <div class="container text-center">
    <div class="col-md-12">
        <div class="card border-dark">
            <h3 class="card-title text-center text-dark card-header">{{ recipe.title }}</h3>
            <div class="card-body text-center text-dark">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-6">
                        <img src="{% static recipe.image.url %}" style="width: inherit;height: auto">
                    </div>
                    <div class="col-md-6 col-sm-6 col-6">

                        <p><b> Ingredients</b> : {{ recipe.ingredients }}</p>
                        <p><b>Description</b> : {{ recipe.description }}</p>
                        {% if user.is_authenticated %}
                            <h4>Rating : {{ average_rating|floatformat:2 }}</h4>
                            {% if not has_rated %}
                                <form action="{% url 'create_rating' recipe.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="number" name="number" required="" id="id_number" min="0" max="5"
                                           class="border-light">

                                    <input type="submit" value="Add rating" class="border-light">
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

    </div>



{% endblock %}

templates/foodies/home_foodies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/foodies/search_foodies.html
{% extends 'base.html' %}
{% load static %}
{% block title %} testing {% endblock %}

{% block content %}

    <br>
    <br>
    <div class="container-fluid text-center">
        <div class="row">
            {% if not recipes %}
                <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-12 text-center">
                        <h2>Ne pare rau reteta nu a fost gasita!!!</h2>
                        <h3>Va rugam mai incercati.</h3>
                        <a href="{% url 'index' %}" class="btn btn-outline-primary">Hit it again !</a>
                    </div>
                </div>
                </div>
            {% endif %}
            {% for recipe in recipes %}
                <div class="col-md-3">
                    <div class="card border-dark mb-3">
                        <h3 class="card-title text-center text-dark card-header" style="height: 9rem">{{ recipe.title }}</h3>
                        <div class="card-body" style="width: 18rem">

                            {% if recipe.image %}
                                <a href="{% url 'detail-view' recipe.id %}"><img src="{% static recipe.image.url %}"
                                                                                 class="card-img-top" width="90rem"
                                                                                 height="190rem"

                                                                                 style="width:-webkit-fill-available"></a>
                            {% else %}
                                <a href="#"> <img src="#" class="card"

                                                  style="width:-webkit-fill-available"></a>

                            {% endif %}

                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </div>
    <br>
    <br>

{% endblock %}